buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // The Android Gradle plugin will be declared in the app module's build.gradle
    }
}

apply plugin: 'java'
apply plugin: 'application'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    // configure the application plugin with the main class
    mainClass = 'com.multipos.Main'
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.multipos.Main'
    }
}
